/********************************************************************
 * ACG
 * All Rights Reserved 
 *
 * File: APP_ACTIVITY_ENUM.java
 ********************************************************************
 *
 *  Ver   Date              Author             Description
 *  ====  ========          ============       ==================
 *  0.1   Aug 29, 2015      Sreeram	       	   Initial Version
/ ********************************************************************/
package com.beingjavaguys.common.enums;

public enum APP_ACTIVITY_ENUM {

	APPLICATION_SUBMITTED(9,"APPLICATION_SUBMITTED"),
	CHALLENGE_QUESTIONS_REQ(10,"CHALLENGE_QUES_REQUESTED"),
	CHALLENGE_QUESTIONS_FAILED(11,"CHALLENGE_QUESTIONS_REQUEST_FAILED"),
	CHALLENGE_QUESTIONS_REC(12,"CHALLENGE_QUES_RECEIVED"),
	TU_AUTHENTICATION_REQUESTED(13,"TU_AUTHENTICATION_REQUESTED"),
	TU_AUTHENTICATION_FAILED(13,"TU_AUTHENTICATION_FAILED"),
	TU_AUTHENTICATION_SUCCESS(14,"TU_AUTHENTICATION_SUCCESS"),
	APPLICATION_FAILED(15,"APPLICATION_FAILED"),	
	APPLICATION_WITHDRAWN(16,"APPLICATION_WITHDRAWN"),
	COLLATERAL_VALUE_REQUESTED(18,"COLLATERAL_REQUESTED"),
	COLLATERAL_VALUE_RECEIVED(19,"COLLATERAL_RECEIVED"),
	COLLATERAL_REQUEST_FAILED(20,"COLLATERAL_REQUEST_FAILED"),
	CRIF_DECISION_REQUESTED(21,"CRIF_DECISION_REQUESTED"),
	CRIF_DECISION_REQ_FAILED(22,"CRIF_DECISION_REQ_FAILED"),
	DECISION_PENDING(23,"DECISION_PENDING"),
	DECISION_READY(24,"DECISION_READY"),
	DECISION_RECEIVED(25,"DECISION_RECEIVED"),
	DECISION_DECLINED(26,"DECISION_DECLINED"),
	DECISION_APPROVED(27,"DECISION_APPROVED"),
	APPLICATION_FULFILLMENT(28,"APPLICATION_FULFILLMENT"),
	FINANCE_INFO_ADDED(29,"FINANCE_INFO_ADDED"),
	DOCS_NOT_GENERATED(30,"DOCUMENTS_NOT_GENERATED"),
	DOCS_GENERATED(31,"DOCUMENTS_GENERATED"),
	DOCS_RECEIVED(32,"DOCUMENTS_RECEIVED"),
	DOCS_ESIGN(33,"DOCUMENTS_ESIGNED"),
	FUNDING_CODE_GEN(34,"FUNDING_CODE_GENERATED"),
	SEND_FUNDING_CODE_DEALER(35,"SEND_CODE_TO_DEALER"),
	DEALER_AUTHENTICATION_SUCCESS(36,"DEALER_AUTHENTICATION_SUCCESS"),
	DEALER_AUTHENTICATION_FAILED(37,"DEALER_AUTHENTICATION_FAILED"),
	FUNDING_REQUESTED(38,"FUNDING_REQUESTED"),
	FUNDING_REQUEST_APPROVED(39,"FUNDING_REQUEST_APPROVED"),
	VALIDATE_DEALER(40,"VALIDATE_DEALER"),
	DEALER_VALIDATED(41,"DEALER_VALIDATED"),
	APP_READY_FOR_BOOKING(42,"APP_READY_FOR_BOOKING"),
	BOOKING_COMPLETED(43,"BOOKING_COMPLETED"),
	FUNDING_INITIATED(44,"FUNDING_INITIATED"),
	LOAN_FUNDED(45,"LOAN_FUNDED"),
	STATUS_UNKNOWN(46,"STATUS UNKNOWN"),
	OFFER_ISNOT_DELIVERED(47,"OFFER_IS_NOT_DELIVERED"),
	SSN_AUTHENTICATION_FAILED_1(48,"SSN_AUTHENTICATION_FAILED_1"),
	SSN_AUTHENTICATION_EXCEEDED(49,"SSN_AUTHENTICATION_EXCEEDED"),
	TU_AUTHENTICATION_ATTEMPTS_EXCEEDED(50,"TU_AUTHENTICATION_ATTEMPTS_EXCEEDED"),
	TU_AUTHENTICATION_BYPASSED(51,"TU_AUTHENTICATION_BYPASSED"),
	SSN_AUTHENTICATION_SUCCESS(52,"SSN_AUTHENTICATION_SUCCESS"),
	CRIF_APPLICATION_CREATED(53,"CRIF_APPLICATION_CREATED"),
	APPLICATION_INITIATED_IN_CRIF(54,"APPLICATION_INITIATED_IN_CRIF"),
	APPLICATION_NOT_CREATED_IN_CRIF(55,"APPLICATION_NOT_CREATED_IN_CRIF"),
	FUNDING_REQUEST_RECEIVED(56,"FUNDING_REQUEST_RECEIVED"),
	PREQUALIFIED_OFFER_NOT_FOUND(57,"PREQUALIFIED_OFFER_NOT_FOUND"),
	ADDRESS_VALIDATION_FAILED(58,"ADDRESS_VALIDATION_FAILED"),
	EXCEEDED_PROPERTY_VALUE(59,"EXCEEDED_PROPERTY_VALUE"),
	EXCEEDED_VENDOR_THRESHOLD_LIMIT(60,"EXCEEDED_VENDOR_THRESHOLD_LIMIT"),
	EXCEEDED_MAX_LTV(61,"EXCEEDED_MAX_LTV"),
	PRIMARY_APPLICANT_SUBMITTED(62,"PRIMARY_APPLICANT_SUBMITTED"),
	TU_OFFER_GENERATED(63,"TU_OFFER_GENERATED"),
	ADDRESS_VALIDATION_FAILED_COBORROWER(66,"ADDRESS_VALIDATION_FAILED_COBORROWER"),
	COBORROWER_CONSENT_PENDING(67,"COBORROWER_CONSENT_PENDING");
	

	private Integer code;
	private String desc;
	
	/**
	 * @return the code
	 */
	public Integer getCode() {
		return code;
	}
	/**
	 * @param code the code to set
	 */
	public void setCode(Integer code) {
		this.code = code;
	}
	/**
	 * @return the description
	 */
	public String getDesc() {
		return desc;
	}
	/**
	 * @param description the description to set
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
	private APP_ACTIVITY_ENUM(Integer code, String desc) {
		this.code = code;
		this.desc = desc;
	}
}
